steps:
  - name: "gcr.io/cloud-builders/docker"
    id: "build-fleet"
    args:
      [
        "build",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/fleet-service:$SHORT_SHA",
        "-t",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/fleet-service:latest",
        "-f",
        "services/fleet/Dockerfile",
        "--platform=linux/amd64",
        ".",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-fleet-sha"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/fleet-service:$SHORT_SHA",
      ]

  - name: "gcr.io/cloud-builders/docker"
    id: "push-fleet-latest"
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/fleet-service:latest",
      ]

  - name: "gcr.io/cloud-builders/gcloud"
    id: "get-gke-credentials"
    args:
      [
        "container",
        "clusters",
        "get-credentials",
        "${_GKE_CLUSTER}",
        "--region",
        "${_GKE_REGION}",
        "--project",
        "$PROJECT_ID",
      ]

  - name: "gcr.io/cloud-builders/kubectl"
    id: "set-fleet-image"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}"
    args:
      [
        "set",
        "image",
        "deployment/fleet-service",
        "fleet-service=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPOSITORY}/fleet-service:$SHORT_SHA",
        "-n",
        "${_K8S_NAMESPACE}",
      ]

  - name: "gcr.io/cloud-builders/kubectl"
    id: "rollout-fleet"
    env:
      - "CLOUDSDK_COMPUTE_REGION=${_GKE_REGION}"
      - "CLOUDSDK_CONTAINER_CLUSTER=${_GKE_CLUSTER}"
    args: ["rollout", "status", "deployment/fleet-service", "-n", "${_K8S_NAMESPACE}"]

substitutions:
  _REGION: "us-east4"
  _AR_REPOSITORY: "image-register"
  _GKE_REGION: "us-east4"
  _GKE_CLUSTER: "CHANGE_ME_CLUSTER_NAME"
  _K8S_NAMESPACE: "school-tracking"

options:
  logging: CLOUD_LOGGING_ONLY
